; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_adalogger
framework = arduino
board_build.core = earlephilhower
upload_protocol = picotool
build_flags = -DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
lib_deps = 
	tomstewart89/BasicLinearAlgebra@^5.1
	adafruit/Adafruit GPS Library@^1.7.5
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit BusIO@^1.16.1
	adafruit/Adafruit BMP3XX Library@^2.1.2
	adafruit/SdFat - Adafruit Fork@^2.3.103
